### ISSUE TITLE
API issues & silent failures

### ISSUE THREAD

**Issue by boneskull** [Losant/losant-mqtt-js#2]
In `device.sendState()`, if the user has not yet called `device.connect()`, this action will fail silently, which is not very nice.  However, emitting an `error` event may be too heavy-handed.

Both an error and a silent failure can be avoided if the MQTT connection is attempted upon creation of the "device" object.

Instead of this API:

```js
const device = Device({id, secret, key, transport});
device.connect(); 
device.sendState(myState);
```

how about:

```js
// mqtt.connect() is called by the factory instead
const device = Device({id, secret, key, transport});
// the mqtt client will enqueue this
device.sendState(myState);
```

Given `device.connect()` does not accept any parameters to modify the connection attempt, it seems to be unnecessary.

* * *

If you don't agree, the `device.connect()` function should probably accept a callback which is called upon the first `connect` event (using `EventEmitter.prototype.once()`) from the MQTT client.  I realize `README.md` suggests subscribing to the `connect` event from the device, but the main example does not show this.  

Think of it as akin to the  `net.createConnection()` API, which accepts some configuration and finally an optional callback:

```js
// these are equivalent
net.createConnection(foo, function onConnect () {});
net.createConncetion(foo).on('connect', function onConnect () {});
```

**Comment by InconceivableDuck** [comment]
I like adding a callback to connect. Will implement that. Will also update examples to recommend calling device.isConnected() prior to sending state.

**Comment by boneskull** [comment]
> I like adding a callback to connect. Will implement that. Will also update examples to recommend calling device.isConnected() prior to sending state.

It's important to note (probably in the docs) that this is *not* a "Node-style", error-first callback.  It's really just an event handler.  A "Node-style" callback cannot be provided in this case, because (IIRC) the MQTT client won't emit `error`--nor will it throw an exception--if the connection attempt "times out".  The client will attempt to connect to the broker indefinitely.

**Comment by InconceivableDuck** [comment]
This is getting added to the gateway branch, which will eventually be merged in as v2.0.0 of this library. Going to wrap up the connect callback to throw the proper error if the connect fails.

**Comment by InconceivableDuck** [comment]
Gateway branch also added a callback error to sendState if the device has never been connected. If the device was connected at anytime, the underlying client will queue it up to be published when it connects again, so no error will be raised.

**Comment by InconceivableDuck** [comment]
I believe v2.0.0 resolves all of your issues. Going to close this one. If you identify others, please create new issues. Thanks!
