### ISSUE TITLE
device.connect requires a callback, but the documentation does not show one

### ISSUE THREAD

**Issue by ottobonn** [Losant/losant-mqtt-js#6]
Calling `device.connect()` as shown in the `README` (that is, calling it with no arguments) causes a `TypeError: callback is not a function` because the callback is unconditionally called in the MQTT client (`lib/mqtt.js`).

**Comment by InconceivableDuck** [comment]
You're right! The callback to connect is a recent change. This client needs updated so the callback is optional.

**Comment by InconceivableDuck** [comment]
This is now fixed in v2.0.1. Thanks!
